// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionGroup } from "./ActionGroup";
import type { Citation } from "./Citation";

/**
 * A single, cited checklist item.
 */
export type ActionItem = { 
/**
 * Which group this belongs to.
 */
group: ActionGroup, 
/**
 * The action, in plain language.
 */
text: string, 
/**
 * Supporting citations (may be empty for generic protective steps).
 */
citations: Array<Citation>, };
