// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionItem } from "./ActionItem";
import type { Conflict } from "./Conflict";
import type { Deadline } from "./Deadline";
import type { InjectionFinding } from "./InjectionFinding";
import type { PaperCard } from "./PaperCard";
import type { TierDecision } from "./TierDecision";

/**
 * The complete analysis result rendered on the dashboard.
 */
export type Analysis = { 
/**
 * Help-tier banner decision.
 */
tier: TierDecision, 
/**
 * Paper card for the notice (the primary document).
 */
paperCard: PaperCard, 
/**
 * Computed deadlines.
 */
deadlines: Array<Deadline>, 
/**
 * Numbered conflicts.
 */
conflicts: Array<Conflict>, 
/**
 * Action checklist.
 */
actions: Array<ActionItem>, 
/**
 * Injection/hidden-text findings surfaced for the user.
 */
findings: Array<InjectionFinding>, 
/**
 * Questions the app still needs answered (e.g. a missing anchor date).
 */
missingInfo: Array<string>, };
