// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reference from a claim to a specific span, with the verbatim quote.
 */
export type Citation = { 
/**
 * The cited span id, e.g. `D1-P2-S3`.
 */
spanId: string, 
/**
 * Verbatim quote from the span (at most 25 words).
 */
quote: string, 
/**
 * 1-based page number, denormalized for display.
 */
page: number, 
/**
 * Similarity score in `[0, 1]` between the quote and the stored span.
 */
similarity: number, 
/**
 * Whether this individual citation was confirmed.
 */
confirmed: boolean, };
