// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Citation } from "./Citation";
import type { VerificationStatus } from "./VerificationStatus";

/**
 * A plain-language statement the model made about the documents.
 */
export type Claim = { 
/**
 * Stable id for cross-referencing (e.g. from a conflict).
 */
id: string, 
/**
 * The plain-language claim text.
 */
text: string, 
/**
 * Supporting citations.
 */
citations: Array<Citation>, 
/**
 * Overall verification status derived from the citations.
 */
status: VerificationStatus, };
