// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Claim } from "./Claim";
import type { Severity } from "./Severity";

/**
 * A conflict between the notice and the agreement.
 */
export type Conflict = { 
/**
 * 1-based conflict number for the UI.
 */
number: number, 
/**
 * Plain-language title, e.g. "Notice period is shorter than agreed".
 */
title: string, 
/**
 * What the notice says, with citation.
 */
noticeSide: Claim, 
/**
 * What the agreement says, with citation.
 */
agreementSide: Claim, 
/**
 * Neutral explanation of the discrepancy (no verdicts).
 */
explanation: string, 
/**
 * Severity, always paired with an icon and word in the UI.
 */
severity: Severity, };
