// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Claim } from "./Claim";
import type { DeadlineCalc } from "./DeadlineCalc";

/**
 * A computed deadline. All arithmetic is done in Rust (chrono), never the model.
 */
export type Deadline = { 
/**
 * What the deadline is for, e.g. "Vacate the premises".
 */
label: string, 
/**
 * The computed date in ISO `YYYY-MM-DD`, if the anchor was known.
 */
date: string | null, 
/**
 * Days remaining from "today", if computable (may be negative).
 */
daysRemaining: number | null, 
/**
 * How the date was derived.
 */
calc: DeadlineCalc, 
/**
 * The claim (with citation) that stated the interval/date.
 */
source: Claim, };
