// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a deadline date was computed, shown to the user step by step.
 */
export type DeadlineCalc = { 
/**
 * Anchor date in ISO `YYYY-MM-DD`, or `None` if unknown.
 */
anchor: string | null, 
/**
 * Human-readable arithmetic, e.g. "2026-09-10 + 7 days".
 */
steps: Array<string>, 
/**
 * Whether the anchor date is missing and must be asked of the user.
 */
needsAnchor: boolean, };
