// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Analysis } from "./Analysis";
import type { Document } from "./Document";
import type { SessionId } from "./SessionId";

/**
 * The result of loading a demo scenario.
 */
export type DemoSession = { 
/**
 * The created session id.
 */
sessionId: SessionId, 
/**
 * The demo documents.
 */
docs: Array<Document>, 
/**
 * The computed analysis.
 */
analysis: Analysis, };
