// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which bundled demo scenario to load.
 */
export type DemoScenarioKind = "eviction" | "scam";
