// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The role a user assigns to an uploaded document.
 */
export type DocRole = "notice" | "myAgreement" | "other";
