// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocRole } from "./DocRole";
import type { SourceKind } from "./SourceKind";
import type { Span } from "./Span";

/**
 * An ingested document, held only in memory for the session.
 */
export type Document = { 
/**
 * 1-based document index used in span ids.
 */
index: number, 
/**
 * Original file name (basename only; never a full path).
 */
fileName: string, 
/**
 * User-assigned role.
 */
role: DocRole, 
/**
 * How the text was obtained.
 */
source: SourceKind, 
/**
 * SHA-256 of the raw bytes, used as a cache key.
 */
hash: string, 
/**
 * Segmented spans, in reading order.
 */
spans: Array<Span>, 
/**
 * Page count.
 */
pageCount: number, };
