// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The three labelled help tiers shown to the user.
 */
export type HelpTier = "information" | "generalGuidance" | "needsLawyer";
