// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a file's content is delivered to the backend.
 */
export type IngestKind = "pdf" | "image";
