// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocRole } from "./DocRole";
import type { IngestKind } from "./IngestKind";
import type { PageInput } from "./PageInput";

/**
 * A single file to ingest. `dataBase64` is the raw file bytes (for magic-byte
 * validation and hashing); PDFs also include `pages` from the worker.
 */
export type IngestFile = { 
/**
 * Original file name (basename only).
 */
fileName: string, 
/**
 * The user-assigned role.
 */
role: DocRole, 
/**
 * How the content is delivered.
 */
kind: IngestKind, 
/**
 * Base64-encoded raw file bytes.
 */
dataBase64: string, 
/**
 * Worker-extracted PDF pages (absent for images).
 */
pages: Array<PageInput> | null, };
