// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A flagged prompt-injection or hidden-text finding for user review.
 */
export type InjectionFinding = { 
/**
 * The span id where the finding occurred.
 */
spanId: string, 
/**
 * Short human-readable reason (e.g. "instruction-like phrase").
 */
reason: string, 
/**
 * The offending excerpt (already PII-masked, at most a few words).
 */
excerpt: string, };
