// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supported UI and content languages.
 */
export type Language = "en" | "ta" | "hi";
