// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One page of already-extracted PDF text (from the Web Worker).
 */
export type PageInput = { 
/**
 * 1-based page number.
 */
number: number, 
/**
 * Extracted text for the page.
 */
text: string, };
