// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single page's worth of extracted text.
 */
export type Page = { 
/**
 * 1-based page number.
 */
number: number, 
/**
 * Full page text (unsegmented), used only for extraction/segmentation.
 */
text: string, };
