// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Claim } from "./Claim";
import type { Party } from "./Party";

/**
 * The "Paper Card": a plain-language summary of what a document is.
 */
export type PaperCard = { 
/**
 * Document type in plain language, e.g. "Eviction notice".
 */
docType: Claim, 
/**
 * Identified parties.
 */
parties: Array<Party>, 
/**
 * One-line plain summary.
 */
summary: Claim, };
