// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Claim } from "./Claim";

/**
 * A named party identified in the documents.
 */
export type Party = { 
/**
 * The party's role, e.g. "Landlord" or "Tenant".
 */
role: string, 
/**
 * The cited claim naming the party (PII-masked as appropriate).
 */
claim: Claim, };
