// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A category of personally identifiable information.
 */
export type PiiKind = "aadhaar" | "pan" | "phone" | "email" | "bankAccount" | "upi";
