// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PiiKind } from "./PiiKind";

/**
 * A detected PII occurrence, by character range, for masking.
 */
export type PiiSpan = { 
/**
 * The kind of PII detected.
 */
kind: PiiKind, 
/**
 * Byte start offset within the analysed text.
 */
start: number, 
/**
 * Byte end offset (exclusive).
 */
end: number, 
/**
 * The masked replacement, e.g. `XXXX-XXXX-1234`.
 */
masked: string, };
