// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Citation } from "./Citation";
import type { QaStatus } from "./QaStatus";

/**
 * A grounded answer to a user question.
 */
export type QaAnswer = { 
/**
 * The answer status pill.
 */
status: QaStatus, 
/**
 * The answer text (empty guidance when not answerable).
 */
text: string, 
/**
 * Supporting citations.
 */
citations: Array<Citation>, };
