// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The status of a grounded Q&A answer.
 */
export type QaStatus = "answered" | "notInDocuments" | "needsLawyer";
