// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Citation } from "./Citation";

/**
 * A drafted neutral reply with footnote citations.
 */
export type ReplyDraft = { 
/**
 * The draft reply text.
 */
text: string, 
/**
 * Footnote citations supporting factual references.
 */
footnotes: Array<Citation>, };
