// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A newtype for opaque, validated identifiers (session, doc references).
 */
export type SessionId = string;
