// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ordered severity for a conflict. Never conveyed by colour alone in the UI.
 */
export type Severity = "low" | "medium" | "high";
