// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a document's text was obtained.
 */
export type SourceKind = "pdfText" | "imageOcr";
