// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpanFlag } from "./SpanFlag";

/**
 * A contiguous, quotable unit of document text with a stable id.
 *
 * The id format is `D{doc}-P{page}-S{n}` (see `services::segmentation`).
 */
export type Span = { 
/**
 * Stable citation id, e.g. `D1-P2-S3`.
 */
id: string, 
/**
 * 1-based document index.
 */
docIndex: number, 
/**
 * 1-based page number.
 */
page: number, 
/**
 * Verbatim text of the span.
 */
text: string, 
/**
 * Any safety flags detected on this span.
 */
flags: Array<SpanFlag>, };
