// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a particular help tier was chosen (shown to the user for transparency).
 */
export type TierReason = "courtOrPolice" | "shortDeadline" | "scamSignal" | "strategyQuestion" | "baseline";
