// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HelpTier } from "./HelpTier";
import type { TierReason } from "./TierReason";

/**
 * The chosen help tier plus the reasons that produced it.
 */
export type TierDecision = { 
/**
 * The resulting tier.
 */
tier: HelpTier, 
/**
 * The reasons that contributed (for transparency).
 */
reasons: Array<TierReason>, };
