// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serializable, localizable error returned to the frontend.
 *
 * `code` maps to an i18n key; `detail` is an optional, PII-free clarifier.
 */
export type UserFacingError = { 
/**
 * Stable i18n key, e.g. `error.limitExceeded`.
 */
code: string, 
/**
 * Optional PII-free clarifier (never contains document text or secrets).
 */
detail: string | null, };
