// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The verification status of a claim after Rust checks its citations.
 */
export type VerificationStatus = "verified" | "notConfirmed";
